name: MapMeel
author: Intro
version: 10.01.2016
main: br.com.introgamer.mapmeel.Main
depend: ['LibsDisguises']

commands:
    stop:
    evento:
    god:
    leiti:
    preferencias:
    scoremanager:
    final:
    minions:
    recarregar:
    confirm:
    cmdtoconsole:
    sfirework:
    cavernaultima:
    sendchat:
    flyspeed:
    walkspeed:
    money:
    dinheiro:
    checkpoint:
    gamemode:
    gm:
    chatpv:
    pvp:
    mlg:
    kit:
    fake:
    tfake:
    transformar:
    check:
    avisoconsole:
    ender:
    errou:
    bc:
    broadcast:
    messagean:
    message:
    jogo:
    invsee:
    jogar:
    permitidos:
    warp:
    reset:
    liberado:
    blockmeel:
    block:
    modoeditor:
    audioteste:
    audio:
    tphere:
    teleport:
    firework:
    gmintro:
    vis:
    textura:
    invis:
    historia: